### PR TITLE
[DRAFT] - Updated to work with bevy 0.9-dev breaking API changes

### PR DESCRIPTION
**Pull request by LarsDu**
The upcoming bevy 0.9 comes with a slew of breaking api changes.
They were substantial enough that I went forward with updating my `bevy_hanabi` branch to work with 0.9

Since 0.9 is a ways away, I'm leaving this as a DRAFT PR for the day when 0.9 lands.

### CODE REVIEW

File: src/render/mod.rs [hunk 1]
```diff
@@ -784,7 +785,7 @@ pub(crate) fn extract_effects(
                         .render_layout
                         .particle_texture
                         .clone()
-                        .map_or(HandleId::default::<Image>(), |handle| handle.id),
+                        .map_or(HandleId::default::<Image>(), |handle| handle.id()),
```
Comment (LarsDu) [inline src/render/mod.rs:788]: Oddly, I'm still getting:
```
error[E0599]: no method named `id` found for struct `bevy::prelude::Handle` in the current scope
   --> /home/ladu/.cargo/git/checkouts/bevy_hanabi-dfe65965bc066065/109fca8/src/render/mod.rs:788:79
    |
788 |                         .map_or(HandleId::default::<Image>(), |handle| handle.id()),
    |                                                                               ^^-- help: remove the arguments
    |                                                                               |
    |                                                                               field, not a method
```

since they made the id field private in the latest bevy

**Comment by djeedai** [comment]
Thanks, this will be valuable when comes the time to update!

**Comment by djeedai** [comment]
Ah so sorry @LarsDu I remembered someone opened a Draft PR for Bevy 0.9 but I thought it was for `bevy_tweening` so I opened #88 myself. 😅

**Comment by djeedai** [comment]
Closing this as 0.5.0 is released with Bevy 0.9 support. Thanks for the help!
